# This Config is used when running swiftlint from within XCode
# It needs to be called from the Example folder "xcode" reporter.
# Make sure the rules are always in sync with the one from ../.swiftlint.yml

disabled_rules:
  - switch_case_alignment
included: # paths to include during linting. `--path` is ignored if present.
 - ../ConsentViewController/Classes
 - ConsentViewController_ExampleTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
identifier_name:
  min_length:
    - 1
    - 1
  allowed_symbols:
    - _
  validates_start_with_lowercase: false
line_length:
  warning: 180
  error: 220
type_name:
  min_length:
    warning: 1
nesting:
  type_level:
    warning: 3
