use_frameworks!
platform :ios, '9.0'

target 'ConsentViewController_Example' do
  pod 'ConsentViewController', :path => '../'
  pod 'SwiftLint'
end

target 'ConsentViewController_ExampleTests' do
  pod 'ConsentViewController', :path => '../'
  pod 'Quick'
  pod 'Nimble'
end

target 'SPGDPRExampleAppUITests' do
  pod 'ConsentViewController', :path => '../'
  pod 'Quick'
  pod 'Nimble'
end

target 'AuthExample' do
  pod 'ConsentViewController', :path => '../'
end

target 'NativeMessageExample' do
  pod 'ConsentViewController', :path => '../'
end

target 'NativeMessageExampleUITests' do
  pod 'ConsentViewController', :path => '../'
  pod 'Quick'
  pod 'Nimble'
end

target 'SourcePointMetaApp' do
  pod 'ConsentViewController', :path => '../'
  pod 'IQKeyboardManagerSwift'
end

target 'SourcePointMetaAppTests' do
  inherit! :search_paths
  # Pods for testing
  pod 'ConsentViewController', :path => '../'
end

