use_frameworks!

target 'ConsentViewController_Example' do
  platform :ios, '9.0'
  pod 'ConsentViewController', :path => '../'
end

target 'AuthExample' do
  platform :ios, '9.0'
  pod 'ConsentViewController', :path => '../'
end

target 'SourcePointMetaApp' do
  pod 'ConsentViewController', :path => '../'
  pod 'IQKeyboardManagerSwift'
end

target 'SourcePointMetaAppTests' do
  inherit! :search_paths
  # Pods for testing
  pod 'ConsentViewController', :path => '../'
end
