#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef CONSENTVIEWCONTROLLER_SWIFT_H
#define CONSENTVIEWCONTROLLER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ConsentViewController",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC21ConsentViewController14AttributeStyle")
@interface AttributeStyle : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Indicates the consent status of a given user.
typedef SWIFT_ENUM(NSInteger, CCPAConsentStatus, open) {
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedNone = 0,
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedSome = 1,
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedAll = 2,
/// Indicates the user has <em>explicitly</em> acceted all vendors and purposes (categories).
/// That’s slightly different than <code>RejectNone</code>. By default in the CCPA users are already
/// <code>RejectedNone</code>, the <code>ConsentedAll</code> indicates the user has taken an action to
/// consent to all vendors and purposes.
  CCPAConsentStatusConsentedAll = 3,
};

@class NSString;
enum SPCampaignType : NSInteger;
@class NSCoder;
@class NSNumber;

SWIFT_CLASS("_TtC21ConsentViewController7SPError")
@interface SPError : NSError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull spDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull failureReason;
@property (nonatomic) NSError * _Nullable originalError;
@property (nonatomic) enum SPCampaignType campaignType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC21ConsentViewController22ConnectionTimeOutError")
@interface ConnectionTimeOutError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



SWIFT_CLASS("_TtC21ConsentViewController11GDPRMessage")
@interface GDPRMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol SPDelegate;
@class NSURL;

SWIFT_PROTOCOL("_TtP21ConsentViewController21GDPRMessageUIDelegate_")
@protocol GDPRMessageUIDelegate
@property (nonatomic, readonly, strong) id <SPDelegate> _Nullable consentDelegate;
- (void)loadMessageFromUrl:(NSURL * _Nonnull)url;
- (void)loadPrivacyManager;
@end

@class NSBundle;

/// The <code>GDPRMessageViewController</code> is the class responsible for rendering the consent
/// message and privacy manager.
/// note:
/// at the moment we only have one child of <code>MessageViewController</code>
/// (<code>MessageWebViewController</code>) but the idea is to be able to swap the webview
/// with any other class that knows how to render a consent message and a privacy manager.
/// Eg. a native message view controller
SWIFT_CLASS("_TtC21ConsentViewController25GDPRMessageViewController")
@interface GDPRMessageViewController : UIViewController <GDPRMessageUIDelegate>
@property (nonatomic, weak) id <SPDelegate> _Nullable consentDelegate;
- (void)loadMessageFromUrl:(NSURL * _Nonnull)url;
- (void)loadPrivacyManager;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21ConsentViewController19GenericNetworkError")
@interface GenericNetworkError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController19InternalServerError")
@interface InternalServerError : GenericNetworkError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController20InvalidArgumentError")
@interface InvalidArgumentError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// Invalid Rendering App (JSReceiver) event payloads
SWIFT_CLASS("_TtC21ConsentViewController24InvalidEventPayloadError")
@interface InvalidEventPayloadError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull failureReason;
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController32InvalidOnActionEventPayloadError")
@interface InvalidOnActionEventPayloadError : InvalidEventPayloadError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


/// Invalid Request Error
SWIFT_CLASS("_TtC21ConsentViewController19InvalidRequestError")
@interface InvalidRequestError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController27InvalidResponseConsentError")
@interface InvalidResponseConsentError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController26InvalidResponseCustomError")
@interface InvalidResponseCustomError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController33InvalidResponseNativeMessageError")
@interface InvalidResponseNativeMessageError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// Invalid API Response Errors
SWIFT_CLASS("_TtC21ConsentViewController30InvalidResponseWebMessageError")
@interface InvalidResponseWebMessageError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController15InvalidURLError")
@interface InvalidURLError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController16MessageAttribute")
@interface MessageAttribute : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ConsentViewController13MessageAction")
@interface MessageAction : MessageAttribute
@end



SWIFT_PROTOCOL("_TtP21ConsentViewController17MessageController_")
@protocol MessageController
- (void)loadMessage;
- (void)loadPrivacyManagerWithUrl:(NSURL * _Nonnull)url;
- (void)closePrivacyManager;
@end


/// Network Errors
SWIFT_CLASS("_TtC21ConsentViewController20NoInternetConnection")
@interface NoInternetConnection : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController32PostingConsentWithoutConsentUUID")
@interface PostingConsentWithoutConsentUUID : InvalidRequestError
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic) enum SPCampaignType campaignType;
@end


SWIFT_CLASS("_TtC21ConsentViewController17RenderingAppError")
@interface RenderingAppError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nullable renderingAppErrorCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController21ResourceNotFoundError")
@interface ResourceNotFoundError : GenericNetworkError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end

enum SPActionType : NSInteger;

/// Action consists of <code>SPActionType</code> and an id. Those come from each action the user can take in the ConsentUI
SWIFT_CLASS("_TtC21ConsentViewController8SPAction")
@interface SPAction : NSObject
@property (nonatomic, readonly) enum SPActionType type;
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable consentLanguage;
@property (nonatomic, copy) NSURL * _Nullable pmURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// User actions. Its integer representation matches with what SourcePoint’s endpoints expect.
typedef SWIFT_ENUM(NSInteger, SPActionType, open) {
  SPActionTypeSaveAndExit = 1,
  SPActionTypePMCancel = 2,
  SPActionTypeAcceptAll = 11,
  SPActionTypeShowPrivacyManager = 12,
  SPActionTypeRejectAll = 13,
  SPActionTypeDismiss = 15,
  SPActionTypeRequestATTAccess = 16,
  SPActionTypeUnknown = 0,
};

enum SPPrivacyManagerTab : NSInteger;

SWIFT_PROTOCOL("_TtP21ConsentViewController6SPCCPA_")
@protocol SPCCPA
- (void)loadCCPAPrivacyManagerWithId:(NSString * _Nonnull)withId tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)ccpaApplies SWIFT_WARN_UNUSED_RESULT;
@end


/// The UserConsent class encapsulates the consent status, rejected vendor ids and rejected categories (purposes) ids.
/// important:
/// The <code>rejectedVendors</code> and <code>rejectedCategories</code> arrays will only be populated if the <code>status</code> is <code>.Some</code>.
/// That is, if the user has rejected <code>.All</code> or <code>.None</code> vendors/categories, those arrays will be empty.
SWIFT_CLASS("_TtC21ConsentViewController13SPCCPAConsent")
@interface SPCCPAConsent : NSObject
/// represents the default state of the consumer prior to seeing the consent message
/// seealso:
/// https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md#us-privacy-string-format
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultUsPrivacyString;)
+ (NSString * _Nonnull)defaultUsPrivacyString SWIFT_WARN_UNUSED_RESULT;
+ (SPCCPAConsent * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
/// Indicates if the user has rejected <code>.All</code>, <code>.Some</code> or <code>.None</code> of the vendors <em>and</em> categories.
@property (nonatomic, readonly) enum CCPAConsentStatus status;
/// The ids of the rejected vendors and categories. These can be found in SourcePoint’s dashboard
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rejectedVendors;
/// The ids of the rejected vendors and categories. These can be found in SourcePoint’s dashboard
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rejectedCategories;
/// the US Privacy String as described by the IAB
@property (nonatomic, readonly, copy) NSString * _Nonnull uspstring;
+ (SPCCPAConsent * _Nonnull)rejectedNone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStatus:(enum CCPAConsentStatus)status rejectedVendors:(NSArray<NSString *> * _Nonnull)rejectedVendors rejectedCategories:(NSArray<NSString *> * _Nonnull)rejectedCategories uspstring:(NSString * _Nonnull)uspstring OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SPCampaignEnv : NSInteger;

/// Contains information about the property/campaign.
SWIFT_CLASS("_TtC21ConsentViewController10SPCampaign")
@interface SPCampaign : NSObject
- (nonnull instancetype)initWithEnvironment:(enum SPCampaignEnv)environment targetingParams:(NSDictionary<NSString *, NSString *> * _Nonnull)targetingParams OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Tells the SDK if we should load stage or public campaigns.
/// <ul>
///   <li>
///     0 -> <code>SPCampaignEnv.Stage</code>
///   </li>
///   <li>
///     1 -> <code>SPCampaignEnv.Public</code>
///   </li>
/// </ul>
typedef SWIFT_ENUM(NSInteger, SPCampaignEnv, open) {
  SPCampaignEnvStage = 0,
  SPCampaignEnvPublic = 1,
};

typedef SWIFT_ENUM(NSInteger, SPCampaignType, open) {
  SPCampaignTypeGdpr = 0,
  SPCampaignTypeIos14 = 1,
  SPCampaignTypeCcpa = 2,
  SPCampaignTypeUnknown = 3,
};


/// Set <code>gdpr</code> and/or <code>ccpa</code> if you wish to cover any of those legislations.
/// It’s important to notice the campaign you passed as parameter needs to have
/// a active vendor list of that legislation.
SWIFT_CLASS("_TtC21ConsentViewController11SPCampaigns")
@interface SPCampaigns : NSObject
- (nonnull instancetype)initWithGdpr:(SPCampaign * _Nullable)gdpr ccpa:(SPCampaign * _Nullable)ccpa ios14:(SPCampaign * _Nullable)ios14 OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SPMessageViewController;
@class SPUserData;

SWIFT_PROTOCOL("_TtP21ConsentViewController17SPConsentDelegate_")
@protocol SPConsentDelegate
/// called when there’s a consent Message to be shown
- (void)onSPUIReady:(SPMessageViewController * _Nonnull)controller;
/// called when the SP UI is finished and can be dismissed
- (void)onSPUIFinished:(SPMessageViewController * _Nonnull)controller;
@optional
/// called after the user takes an action and the SDK receives consent data back from the server
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     consents: is the consent profile
///   </li>
/// </ul>
- (void)onConsentReadyWithUserData:(SPUserData * _Nonnull)userData;
/// called if something goes wrong during the entire lifecycle of the SDK
- (void)onErrorWithError:(SPError * _Nonnull)error;
@end


SWIFT_PROTOCOL("_TtP21ConsentViewController6SPGDPR_")
@protocol SPGDPR
- (void)loadGDPRPrivacyManagerWithId:(NSString * _Nonnull)withId tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)gdprApplies SWIFT_WARN_UNUSED_RESULT;
@end

@class SPGDPRConsent;

SWIFT_PROTOCOL("_TtP21ConsentViewController5SPSDK_")
@protocol SPSDK <SPCCPA, SPGDPR>
@property (nonatomic, readonly, strong) SPUserData * _Nonnull userData;
- (void)loadMessageForAuthId:(NSString * _Nullable)authId;
- (void)customConsentGDPRWithVendors:(NSArray<NSString *> * _Nonnull)vendors categories:(NSArray<NSString *> * _Nonnull)categories legIntCategories:(NSArray<NSString *> * _Nonnull)legIntCategories handler:(void (^ _Nonnull)(SPGDPRConsent * _Nonnull))handler;
@end

@class SPPropertyName;
enum SPMessageLanguage : NSInteger;

SWIFT_CLASS("_TtC21ConsentViewController16SPConsentManager")
@interface SPConsentManager : NSObject <SPSDK>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VERSION;)
+ (NSString * _Nonnull)VERSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL shouldCallErrorMetrics;)
+ (BOOL)shouldCallErrorMetrics SWIFT_WARN_UNUSED_RESULT;
+ (void)setShouldCallErrorMetrics:(BOOL)value;
@property (nonatomic, readonly, strong) SPUserData * _Nonnull userData;
+ (void)clearAllData;
- (nonnull instancetype)initWithAccountId:(NSInteger)accountId propertyName:(SPPropertyName * _Nonnull)propertyName campaigns:(SPCampaigns * _Nonnull)campaigns delegate:(id <SPDelegate> _Nullable)delegate;
/// Instructs the privacy manager to be displayed with this tab.
/// By default the SDK will use the defult tab of PM
@property (nonatomic) enum SPPrivacyManagerTab privacyManagerTab;
/// Instructs the message to be displayed in this language. If the translation is missing, the fallback will be English.
/// By default the SDK will use the locale defined by the WebView
@property (nonatomic) enum SPMessageLanguage messageLanguage;
- (void)loadMessageForAuthId:(NSString * _Nullable)authId;
- (void)loadGDPRPrivacyManagerWithId:(NSString * _Nonnull)id tab:(enum SPPrivacyManagerTab)tab;
- (void)loadCCPAPrivacyManagerWithId:(NSString * _Nonnull)id tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)gdprApplies SWIFT_WARN_UNUSED_RESULT;
- (BOOL)ccpaApplies SWIFT_WARN_UNUSED_RESULT;
- (void)customConsentGDPRWithVendors:(NSArray<NSString *> * _Nonnull)vendors categories:(NSArray<NSString *> * _Nonnull)categories legIntCategories:(NSArray<NSString *> * _Nonnull)legIntCategories handler:(void (^ _Nonnull)(SPGDPRConsent * _Nonnull))handler;
- (void)onError:(SPError * _Nonnull)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP21ConsentViewController19SPConsentUIDelegate_")
@protocol SPConsentUIDelegate
/// called when the user takes an action in the SP UI
/// \param action the user action
///
- (void)onAction:(SPAction * _Nonnull)action from:(SPMessageViewController * _Nonnull)controller;
@end


/// Have a look at <a href="https://github.com/SourcePointUSA/CCPA_iOS_SDK/wiki/SDKs-Lifecycle-methods">SDKs Lifecycle</a>
SWIFT_PROTOCOL("_TtP21ConsentViewController10SPDelegate_")
@protocol SPDelegate <SPConsentDelegate, SPConsentUIDelegate>
@end



@class SPGDPRVendorGrant;

/// SPGDPRConsent encapsulates all consent data from a user.
SWIFT_CLASS("_TtC21ConsentViewController13SPGDPRConsent")
@interface SPGDPRConsent : NSObject
+ (SPGDPRConsent * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, SPGDPRVendorGrant *> * _Nonnull vendorGrants;
/// The iAB consent string.
@property (nonatomic, readonly, copy) NSString * _Nonnull euconsent;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Encapuslates data about a particular vendor being “granted” based on its purposes
SWIFT_CLASS("_TtC21ConsentViewController17SPGDPRVendorGrant")
@interface SPGDPRVendorGrant : NSObject
/// if all purposes are granted, the vendorGrant will be set to <code>true</code>
@property (nonatomic, readonly) BOOL granted;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSNumber *> * _Nonnull purposeGrants;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithGranted:(BOOL)granted purposeGrants:(NSDictionary<NSString *, NSNumber *> * _Nonnull)purposeGrants OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Maps <code>ATTrackingManager.requestTrackingAuthorization</code> into our own enum.
/// It covers also the case when <code>ATTrackingManager.AuthorizationStatus</code> is not available.
typedef SWIFT_ENUM(NSInteger, SPIDFAStatus, open) {
/// the user hasn’t been prompted about the IDFA yet
  SPIDFAStatusUnknown = 0,
/// the user accepted being tracked
  SPIDFAStatusAccepted = 1,
/// the user denied access to IDFA
  SPIDFAStatusDenied = 2,
/// the IDFA is not available in this version of the OS
  SPIDFAStatusUnavailable = 3,
};

/// Languages supported by Message and PM
typedef SWIFT_ENUM(NSInteger, SPMessageLanguage, open) {
  SPMessageLanguageBrowserDefault = 0,
  SPMessageLanguageEnglish = 1,
  SPMessageLanguageBulgarian = 2,
  SPMessageLanguageCatalan = 3,
  SPMessageLanguageChinese = 4,
  SPMessageLanguageCroatian = 5,
  SPMessageLanguageCzech = 6,
  SPMessageLanguageDanish = 7,
  SPMessageLanguageDutch = 8,
  SPMessageLanguageEstonian = 9,
  SPMessageLanguageFinnish = 10,
  SPMessageLanguageFrench = 11,
  SPMessageLanguageGaelic = 12,
  SPMessageLanguageGerman = 13,
  SPMessageLanguageGreek = 14,
  SPMessageLanguageHungarian = 15,
  SPMessageLanguageIcelandic = 16,
  SPMessageLanguageItalian = 17,
  SPMessageLanguageJapanese = 18,
  SPMessageLanguageLatvian = 19,
  SPMessageLanguageLithuanian = 20,
  SPMessageLanguageNorwegian = 21,
  SPMessageLanguagePolish = 22,
  SPMessageLanguagePortuguese = 23,
  SPMessageLanguageRomanian = 24,
  SPMessageLanguageRussian = 25,
  SPMessageLanguageSerbian_Cyrillic = 26,
  SPMessageLanguageSerbian_Latin = 27,
  SPMessageLanguageSlovakian = 28,
  SPMessageLanguageSlovenian = 29,
  SPMessageLanguageSpanish = 30,
  SPMessageLanguageSwedish = 31,
  SPMessageLanguageTurkish = 32,
};


SWIFT_CLASS("_TtC21ConsentViewController23SPMessageViewController")
@interface SPMessageViewController : UIViewController <MessageController>
@property (nonatomic) enum SPCampaignType campaignType;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)loadMessage;
- (void)loadPrivacyManagerWithUrl:(NSURL * _Nonnull)url;
- (void)closePrivacyManager;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC21ConsentViewController29SPNativeMessageViewController")
@interface SPNativeMessageViewController : SPMessageViewController
- (nullable instancetype)initWithMessageContents:(GDPRMessage * _Nonnull)messageContents consentViewController:(id <GDPRMessageUIDelegate> _Nonnull)consentViewController OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@end

/// Supported privacy manager tabs in PM
typedef SWIFT_ENUM(NSInteger, SPPrivacyManagerTab, open) {
  SPPrivacyManagerTabDefault = 0,
  SPPrivacyManagerTabPurposes = 1,
  SPPrivacyManagerTabVendors = 2,
  SPPrivacyManagerTabFeatures = 3,
};


/// SPPropertyName is the exact name of your property as created in SourcePoint’s dashboard.
/// important:
/// notice that it can only contain letters, numbers, . (dots), : (semicolons),
/// <ul>
///   <li>
///     (dashes) and / (slashes). The constructor will validate upon that and throw an error otherwise.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC21ConsentViewController14SPPropertyName")
@interface SPPropertyName : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// \param rawValue the exact name of your property as created in SourcePoint’s dashboard.
///
///
/// throws:
/// <code>InvalidArgumentError</code> if the property name contain anything other than letters, numbers, . (dots), : (semicolons) and / (slashes).
- (nullable instancetype)init:(NSString * _Nonnull)rawValue error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21ConsentViewController10SPUserData")
@interface SPUserData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC21ConsentViewController37UnableToInjectMessageIntoRenderingApp")
@interface UnableToInjectMessageIntoRenderingApp : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController22UnableToLoadJSReceiver")
@interface UnableToLoadJSReceiver : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



@interface WKWebView (SWIFT_EXTENSION(ConsentViewController))
/// Injects the cookie <code>authId</code> in the webview before loading its content.
/// SourcePoint’s web SDK reads the <code>authId</code> cookie and set everything up in the webview context.
- (void)setConsentForAuthId:(NSString * _Nonnull)authId;
/// Reads the value of the cookie authId
- (void)getAuthIdWithCompletionHandler:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC21ConsentViewController12WebViewError")
@interface WebViewError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef CONSENTVIEWCONTROLLER_SWIFT_H
#define CONSENTVIEWCONTROLLER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ConsentViewController",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC21ConsentViewController14AttributeStyle")
@interface AttributeStyle : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Indicates the consent status of a given user.
typedef SWIFT_ENUM(NSInteger, CCPAConsentStatus, open) {
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedNone = 0,
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedSome = 1,
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedAll = 2,
/// Indicates the user has <em>explicitly</em> acceted all vendors and purposes (categories).
/// That’s slightly different than <code>RejectNone</code>. By default in the CCPA users are already
/// <code>RejectedNone</code>, the <code>ConsentedAll</code> indicates the user has taken an action to
/// consent to all vendors and purposes.
  CCPAConsentStatusConsentedAll = 3,
};

@class NSString;
enum SPCampaignType : NSInteger;
@class NSCoder;
@class NSNumber;

SWIFT_CLASS("_TtC21ConsentViewController7SPError")
@interface SPError : NSError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull spDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull failureReason;
@property (nonatomic) NSError * _Nullable originalError;
@property (nonatomic) enum SPCampaignType campaignType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC21ConsentViewController22ConnectionTimeOutError")
@interface ConnectionTimeOutError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



SWIFT_CLASS("_TtC21ConsentViewController11GDPRMessage")
@interface GDPRMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol SPDelegate;
@class NSURL;

SWIFT_PROTOCOL("_TtP21ConsentViewController21GDPRMessageUIDelegate_")
@protocol GDPRMessageUIDelegate
@property (nonatomic, readonly, strong) id <SPDelegate> _Nullable consentDelegate;
- (void)loadMessageFromUrl:(NSURL * _Nonnull)url;
- (void)loadPrivacyManager;
@end

@class NSBundle;

/// The <code>GDPRMessageViewController</code> is the class responsible for rendering the consent
/// message and privacy manager.
/// note:
/// at the moment we only have one child of <code>MessageViewController</code>
/// (<code>MessageWebViewController</code>) but the idea is to be able to swap the webview
/// with any other class that knows how to render a consent message and a privacy manager.
/// Eg. a native message view controller
SWIFT_CLASS("_TtC21ConsentViewController25GDPRMessageViewController")
@interface GDPRMessageViewController : UIViewController <GDPRMessageUIDelegate>
@property (nonatomic, weak) id <SPDelegate> _Nullable consentDelegate;
- (void)loadMessageFromUrl:(NSURL * _Nonnull)url;
- (void)loadPrivacyManager;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21ConsentViewController19GenericNetworkError")
@interface GenericNetworkError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController19InternalServerError")
@interface InternalServerError : GenericNetworkError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController20InvalidArgumentError")
@interface InvalidArgumentError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// Invalid Rendering App (JSReceiver) event payloads
SWIFT_CLASS("_TtC21ConsentViewController24InvalidEventPayloadError")
@interface InvalidEventPayloadError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull failureReason;
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController32InvalidOnActionEventPayloadError")
@interface InvalidOnActionEventPayloadError : InvalidEventPayloadError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


/// Invalid Request Error
SWIFT_CLASS("_TtC21ConsentViewController19InvalidRequestError")
@interface InvalidRequestError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController27InvalidResponseConsentError")
@interface InvalidResponseConsentError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController26InvalidResponseCustomError")
@interface InvalidResponseCustomError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController33InvalidResponseNativeMessageError")
@interface InvalidResponseNativeMessageError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// Invalid API Response Errors
SWIFT_CLASS("_TtC21ConsentViewController30InvalidResponseWebMessageError")
@interface InvalidResponseWebMessageError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController15InvalidURLError")
@interface InvalidURLError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController16MessageAttribute")
@interface MessageAttribute : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ConsentViewController13MessageAction")
@interface MessageAction : MessageAttribute
@end



SWIFT_PROTOCOL("_TtP21ConsentViewController17MessageController_")
@protocol MessageController
- (void)loadMessage;
- (void)loadPrivacyManagerWithUrl:(NSURL * _Nonnull)url;
- (void)closePrivacyManager;
@end


/// Network Errors
SWIFT_CLASS("_TtC21ConsentViewController20NoInternetConnection")
@interface NoInternetConnection : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController32PostingConsentWithoutConsentUUID")
@interface PostingConsentWithoutConsentUUID : InvalidRequestError
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic) enum SPCampaignType campaignType;
@end


SWIFT_CLASS("_TtC21ConsentViewController17RenderingAppError")
@interface RenderingAppError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nullable renderingAppErrorCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController21ResourceNotFoundError")
@interface ResourceNotFoundError : GenericNetworkError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end

enum SPActionType : NSInteger;

/// Action consists of <code>SPActionType</code> and an id. Those come from each action the user can take in the ConsentUI
SWIFT_CLASS("_TtC21ConsentViewController8SPAction")
@interface SPAction : NSObject
@property (nonatomic, readonly) enum SPActionType type;
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable consentLanguage;
@property (nonatomic, copy) NSURL * _Nullable pmURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// User actions. Its integer representation matches with what SourcePoint’s endpoints expect.
typedef SWIFT_ENUM(NSInteger, SPActionType, open) {
  SPActionTypeSaveAndExit = 1,
  SPActionTypePMCancel = 2,
  SPActionTypeAcceptAll = 11,
  SPActionTypeShowPrivacyManager = 12,
  SPActionTypeRejectAll = 13,
  SPActionTypeDismiss = 15,
  SPActionTypeRequestATTAccess = 16,
  SPActionTypeUnknown = 0,
};

enum SPPrivacyManagerTab : NSInteger;

SWIFT_PROTOCOL("_TtP21ConsentViewController6SPCCPA_")
@protocol SPCCPA
- (void)loadCCPAPrivacyManagerWithId:(NSString * _Nonnull)withId tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)ccpaApplies SWIFT_WARN_UNUSED_RESULT;
@end


/// The UserConsent class encapsulates the consent status, rejected vendor ids and rejected categories (purposes) ids.
/// important:
/// The <code>rejectedVendors</code> and <code>rejectedCategories</code> arrays will only be populated if the <code>status</code> is <code>.Some</code>.
/// That is, if the user has rejected <code>.All</code> or <code>.None</code> vendors/categories, those arrays will be empty.
SWIFT_CLASS("_TtC21ConsentViewController13SPCCPAConsent")
@interface SPCCPAConsent : NSObject
/// represents the default state of the consumer prior to seeing the consent message
/// seealso:
/// https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md#us-privacy-string-format
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultUsPrivacyString;)
+ (NSString * _Nonnull)defaultUsPrivacyString SWIFT_WARN_UNUSED_RESULT;
+ (SPCCPAConsent * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
/// Indicates if the user has rejected <code>.All</code>, <code>.Some</code> or <code>.None</code> of the vendors <em>and</em> categories.
@property (nonatomic, readonly) enum CCPAConsentStatus status;
/// The ids of the rejected vendors and categories. These can be found in SourcePoint’s dashboard
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rejectedVendors;
/// The ids of the rejected vendors and categories. These can be found in SourcePoint’s dashboard
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rejectedCategories;
/// the US Privacy String as described by the IAB
@property (nonatomic, readonly, copy) NSString * _Nonnull uspstring;
+ (SPCCPAConsent * _Nonnull)rejectedNone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStatus:(enum CCPAConsentStatus)status rejectedVendors:(NSArray<NSString *> * _Nonnull)rejectedVendors rejectedCategories:(NSArray<NSString *> * _Nonnull)rejectedCategories uspstring:(NSString * _Nonnull)uspstring OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SPCampaignEnv : NSInteger;

/// Contains information about the property/campaign.
SWIFT_CLASS("_TtC21ConsentViewController10SPCampaign")
@interface SPCampaign : NSObject
- (nonnull instancetype)initWithEnvironment:(enum SPCampaignEnv)environment targetingParams:(NSDictionary<NSString *, NSString *> * _Nonnull)targetingParams OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Tells the SDK if we should load stage or public campaigns.
/// <ul>
///   <li>
///     0 -> <code>SPCampaignEnv.Stage</code>
///   </li>
///   <li>
///     1 -> <code>SPCampaignEnv.Public</code>
///   </li>
/// </ul>
typedef SWIFT_ENUM(NSInteger, SPCampaignEnv, open) {
  SPCampaignEnvStage = 0,
  SPCampaignEnvPublic = 1,
};

typedef SWIFT_ENUM(NSInteger, SPCampaignType, open) {
  SPCampaignTypeGdpr = 0,
  SPCampaignTypeIos14 = 1,
  SPCampaignTypeCcpa = 2,
  SPCampaignTypeUnknown = 3,
};


/// Set <code>gdpr</code> and/or <code>ccpa</code> if you wish to cover any of those legislations.
/// It’s important to notice the campaign you passed as parameter needs to have
/// a active vendor list of that legislation.
SWIFT_CLASS("_TtC21ConsentViewController11SPCampaigns")
@interface SPCampaigns : NSObject
- (nonnull instancetype)initWithGdpr:(SPCampaign * _Nullable)gdpr ccpa:(SPCampaign * _Nullable)ccpa ios14:(SPCampaign * _Nullable)ios14 OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SPMessageViewController;
@class SPUserData;

SWIFT_PROTOCOL("_TtP21ConsentViewController17SPConsentDelegate_")
@protocol SPConsentDelegate
/// called when there’s a consent Message to be shown
- (void)onSPUIReady:(SPMessageViewController * _Nonnull)controller;
/// called when the SP UI is finished and can be dismissed
- (void)onSPUIFinished:(SPMessageViewController * _Nonnull)controller;
@optional
/// called after the user takes an action and the SDK receives consent data back from the server
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     consents: is the consent profile
///   </li>
/// </ul>
- (void)onConsentReadyWithUserData:(SPUserData * _Nonnull)userData;
/// called if something goes wrong during the entire lifecycle of the SDK
- (void)onErrorWithError:(SPError * _Nonnull)error;
@end


SWIFT_PROTOCOL("_TtP21ConsentViewController6SPGDPR_")
@protocol SPGDPR
- (void)loadGDPRPrivacyManagerWithId:(NSString * _Nonnull)withId tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)gdprApplies SWIFT_WARN_UNUSED_RESULT;
@end

@class SPGDPRConsent;

SWIFT_PROTOCOL("_TtP21ConsentViewController5SPSDK_")
@protocol SPSDK <SPCCPA, SPGDPR>
@property (nonatomic, readonly, strong) SPUserData * _Nonnull userData;
- (void)loadMessageForAuthId:(NSString * _Nullable)authId;
- (void)customConsentGDPRWithVendors:(NSArray<NSString *> * _Nonnull)vendors categories:(NSArray<NSString *> * _Nonnull)categories legIntCategories:(NSArray<NSString *> * _Nonnull)legIntCategories handler:(void (^ _Nonnull)(SPGDPRConsent * _Nonnull))handler;
@end

@class SPPropertyName;
enum SPMessageLanguage : NSInteger;

SWIFT_CLASS("_TtC21ConsentViewController16SPConsentManager")
@interface SPConsentManager : NSObject <SPSDK>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VERSION;)
+ (NSString * _Nonnull)VERSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL shouldCallErrorMetrics;)
+ (BOOL)shouldCallErrorMetrics SWIFT_WARN_UNUSED_RESULT;
+ (void)setShouldCallErrorMetrics:(BOOL)value;
@property (nonatomic, readonly, strong) SPUserData * _Nonnull userData;
+ (void)clearAllData;
- (nonnull instancetype)initWithAccountId:(NSInteger)accountId propertyName:(SPPropertyName * _Nonnull)propertyName campaigns:(SPCampaigns * _Nonnull)campaigns delegate:(id <SPDelegate> _Nullable)delegate;
/// Instructs the privacy manager to be displayed with this tab.
/// By default the SDK will use the defult tab of PM
@property (nonatomic) enum SPPrivacyManagerTab privacyManagerTab;
/// Instructs the message to be displayed in this language. If the translation is missing, the fallback will be English.
/// By default the SDK will use the locale defined by the WebView
@property (nonatomic) enum SPMessageLanguage messageLanguage;
- (void)loadMessageForAuthId:(NSString * _Nullable)authId;
- (void)loadGDPRPrivacyManagerWithId:(NSString * _Nonnull)id tab:(enum SPPrivacyManagerTab)tab;
- (void)loadCCPAPrivacyManagerWithId:(NSString * _Nonnull)id tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)gdprApplies SWIFT_WARN_UNUSED_RESULT;
- (BOOL)ccpaApplies SWIFT_WARN_UNUSED_RESULT;
- (void)customConsentGDPRWithVendors:(NSArray<NSString *> * _Nonnull)vendors categories:(NSArray<NSString *> * _Nonnull)categories legIntCategories:(NSArray<NSString *> * _Nonnull)legIntCategories handler:(void (^ _Nonnull)(SPGDPRConsent * _Nonnull))handler;
- (void)onError:(SPError * _Nonnull)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP21ConsentViewController19SPConsentUIDelegate_")
@protocol SPConsentUIDelegate
/// called when the user takes an action in the SP UI
/// \param action the user action
///
- (void)onAction:(SPAction * _Nonnull)action from:(SPMessageViewController * _Nonnull)controller;
@end


/// Have a look at <a href="https://github.com/SourcePointUSA/CCPA_iOS_SDK/wiki/SDKs-Lifecycle-methods">SDKs Lifecycle</a>
SWIFT_PROTOCOL("_TtP21ConsentViewController10SPDelegate_")
@protocol SPDelegate <SPConsentDelegate, SPConsentUIDelegate>
@end



@class SPGDPRVendorGrant;

/// SPGDPRConsent encapsulates all consent data from a user.
SWIFT_CLASS("_TtC21ConsentViewController13SPGDPRConsent")
@interface SPGDPRConsent : NSObject
+ (SPGDPRConsent * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, SPGDPRVendorGrant *> * _Nonnull vendorGrants;
/// The iAB consent string.
@property (nonatomic, readonly, copy) NSString * _Nonnull euconsent;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Encapuslates data about a particular vendor being “granted” based on its purposes
SWIFT_CLASS("_TtC21ConsentViewController17SPGDPRVendorGrant")
@interface SPGDPRVendorGrant : NSObject
/// if all purposes are granted, the vendorGrant will be set to <code>true</code>
@property (nonatomic, readonly) BOOL granted;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSNumber *> * _Nonnull purposeGrants;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithGranted:(BOOL)granted purposeGrants:(NSDictionary<NSString *, NSNumber *> * _Nonnull)purposeGrants OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Maps <code>ATTrackingManager.requestTrackingAuthorization</code> into our own enum.
/// It covers also the case when <code>ATTrackingManager.AuthorizationStatus</code> is not available.
typedef SWIFT_ENUM(NSInteger, SPIDFAStatus, open) {
/// the user hasn’t been prompted about the IDFA yet
  SPIDFAStatusUnknown = 0,
/// the user accepted being tracked
  SPIDFAStatusAccepted = 1,
/// the user denied access to IDFA
  SPIDFAStatusDenied = 2,
/// the IDFA is not available in this version of the OS
  SPIDFAStatusUnavailable = 3,
};

/// Languages supported by Message and PM
typedef SWIFT_ENUM(NSInteger, SPMessageLanguage, open) {
  SPMessageLanguageBrowserDefault = 0,
  SPMessageLanguageEnglish = 1,
  SPMessageLanguageBulgarian = 2,
  SPMessageLanguageCatalan = 3,
  SPMessageLanguageChinese = 4,
  SPMessageLanguageCroatian = 5,
  SPMessageLanguageCzech = 6,
  SPMessageLanguageDanish = 7,
  SPMessageLanguageDutch = 8,
  SPMessageLanguageEstonian = 9,
  SPMessageLanguageFinnish = 10,
  SPMessageLanguageFrench = 11,
  SPMessageLanguageGaelic = 12,
  SPMessageLanguageGerman = 13,
  SPMessageLanguageGreek = 14,
  SPMessageLanguageHungarian = 15,
  SPMessageLanguageIcelandic = 16,
  SPMessageLanguageItalian = 17,
  SPMessageLanguageJapanese = 18,
  SPMessageLanguageLatvian = 19,
  SPMessageLanguageLithuanian = 20,
  SPMessageLanguageNorwegian = 21,
  SPMessageLanguagePolish = 22,
  SPMessageLanguagePortuguese = 23,
  SPMessageLanguageRomanian = 24,
  SPMessageLanguageRussian = 25,
  SPMessageLanguageSerbian_Cyrillic = 26,
  SPMessageLanguageSerbian_Latin = 27,
  SPMessageLanguageSlovakian = 28,
  SPMessageLanguageSlovenian = 29,
  SPMessageLanguageSpanish = 30,
  SPMessageLanguageSwedish = 31,
  SPMessageLanguageTurkish = 32,
};


SWIFT_CLASS("_TtC21ConsentViewController23SPMessageViewController")
@interface SPMessageViewController : UIViewController <MessageController>
@property (nonatomic) enum SPCampaignType campaignType;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)loadMessage;
- (void)loadPrivacyManagerWithUrl:(NSURL * _Nonnull)url;
- (void)closePrivacyManager;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC21ConsentViewController29SPNativeMessageViewController")
@interface SPNativeMessageViewController : SPMessageViewController
- (nullable instancetype)initWithMessageContents:(GDPRMessage * _Nonnull)messageContents consentViewController:(id <GDPRMessageUIDelegate> _Nonnull)consentViewController OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@end

/// Supported privacy manager tabs in PM
typedef SWIFT_ENUM(NSInteger, SPPrivacyManagerTab, open) {
  SPPrivacyManagerTabDefault = 0,
  SPPrivacyManagerTabPurposes = 1,
  SPPrivacyManagerTabVendors = 2,
  SPPrivacyManagerTabFeatures = 3,
};


/// SPPropertyName is the exact name of your property as created in SourcePoint’s dashboard.
/// important:
/// notice that it can only contain letters, numbers, . (dots), : (semicolons),
/// <ul>
///   <li>
///     (dashes) and / (slashes). The constructor will validate upon that and throw an error otherwise.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC21ConsentViewController14SPPropertyName")
@interface SPPropertyName : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// \param rawValue the exact name of your property as created in SourcePoint’s dashboard.
///
///
/// throws:
/// <code>InvalidArgumentError</code> if the property name contain anything other than letters, numbers, . (dots), : (semicolons) and / (slashes).
- (nullable instancetype)init:(NSString * _Nonnull)rawValue error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21ConsentViewController10SPUserData")
@interface SPUserData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC21ConsentViewController37UnableToInjectMessageIntoRenderingApp")
@interface UnableToInjectMessageIntoRenderingApp : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController22UnableToLoadJSReceiver")
@interface UnableToLoadJSReceiver : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



@interface WKWebView (SWIFT_EXTENSION(ConsentViewController))
/// Injects the cookie <code>authId</code> in the webview before loading its content.
/// SourcePoint’s web SDK reads the <code>authId</code> cookie and set everything up in the webview context.
- (void)setConsentForAuthId:(NSString * _Nonnull)authId;
/// Reads the value of the cookie authId
- (void)getAuthIdWithCompletionHandler:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC21ConsentViewController12WebViewError")
@interface WebViewError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef CONSENTVIEWCONTROLLER_SWIFT_H
#define CONSENTVIEWCONTROLLER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ConsentViewController",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC21ConsentViewController14AttributeStyle")
@interface AttributeStyle : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Indicates the consent status of a given user.
typedef SWIFT_ENUM(NSInteger, CCPAConsentStatus, open) {
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedNone = 0,
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedSome = 1,
/// Indicates the user has rejected none of the vendors or purposes (categories)
  CCPAConsentStatusRejectedAll = 2,
/// Indicates the user has <em>explicitly</em> acceted all vendors and purposes (categories).
/// That’s slightly different than <code>RejectNone</code>. By default in the CCPA users are already
/// <code>RejectedNone</code>, the <code>ConsentedAll</code> indicates the user has taken an action to
/// consent to all vendors and purposes.
  CCPAConsentStatusConsentedAll = 3,
};

@class NSString;
enum SPCampaignType : NSInteger;
@class NSCoder;
@class NSNumber;

SWIFT_CLASS("_TtC21ConsentViewController7SPError")
@interface SPError : NSError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull spDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull failureReason;
@property (nonatomic) NSError * _Nullable originalError;
@property (nonatomic) enum SPCampaignType campaignType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC21ConsentViewController22ConnectionTimeOutError")
@interface ConnectionTimeOutError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



SWIFT_CLASS("_TtC21ConsentViewController11GDPRMessage")
@interface GDPRMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol SPDelegate;
@class NSURL;

SWIFT_PROTOCOL("_TtP21ConsentViewController21GDPRMessageUIDelegate_")
@protocol GDPRMessageUIDelegate
@property (nonatomic, readonly, strong) id <SPDelegate> _Nullable consentDelegate;
- (void)loadMessageFromUrl:(NSURL * _Nonnull)url;
- (void)loadPrivacyManager;
@end

@class NSBundle;

/// The <code>GDPRMessageViewController</code> is the class responsible for rendering the consent
/// message and privacy manager.
/// note:
/// at the moment we only have one child of <code>MessageViewController</code>
/// (<code>MessageWebViewController</code>) but the idea is to be able to swap the webview
/// with any other class that knows how to render a consent message and a privacy manager.
/// Eg. a native message view controller
SWIFT_CLASS("_TtC21ConsentViewController25GDPRMessageViewController")
@interface GDPRMessageViewController : UIViewController <GDPRMessageUIDelegate>
@property (nonatomic, weak) id <SPDelegate> _Nullable consentDelegate;
- (void)loadMessageFromUrl:(NSURL * _Nonnull)url;
- (void)loadPrivacyManager;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21ConsentViewController19GenericNetworkError")
@interface GenericNetworkError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController19InternalServerError")
@interface InternalServerError : GenericNetworkError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController20InvalidArgumentError")
@interface InvalidArgumentError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// Invalid Rendering App (JSReceiver) event payloads
SWIFT_CLASS("_TtC21ConsentViewController24InvalidEventPayloadError")
@interface InvalidEventPayloadError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull failureReason;
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController32InvalidOnActionEventPayloadError")
@interface InvalidOnActionEventPayloadError : InvalidEventPayloadError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


/// Invalid Request Error
SWIFT_CLASS("_TtC21ConsentViewController19InvalidRequestError")
@interface InvalidRequestError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController27InvalidResponseConsentError")
@interface InvalidResponseConsentError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController26InvalidResponseCustomError")
@interface InvalidResponseCustomError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController33InvalidResponseNativeMessageError")
@interface InvalidResponseNativeMessageError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// Invalid API Response Errors
SWIFT_CLASS("_TtC21ConsentViewController30InvalidResponseWebMessageError")
@interface InvalidResponseWebMessageError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController15InvalidURLError")
@interface InvalidURLError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController16MessageAttribute")
@interface MessageAttribute : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ConsentViewController13MessageAction")
@interface MessageAction : MessageAttribute
@end



SWIFT_PROTOCOL("_TtP21ConsentViewController17MessageController_")
@protocol MessageController
- (void)loadMessage;
- (void)loadPrivacyManagerWithUrl:(NSURL * _Nonnull)url;
- (void)closePrivacyManager;
@end


/// Network Errors
SWIFT_CLASS("_TtC21ConsentViewController20NoInternetConnection")
@interface NoInternetConnection : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController32PostingConsentWithoutConsentUUID")
@interface PostingConsentWithoutConsentUUID : InvalidRequestError
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic) enum SPCampaignType campaignType;
@end


SWIFT_CLASS("_TtC21ConsentViewController17RenderingAppError")
@interface RenderingAppError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nullable renderingAppErrorCode;
@end


SWIFT_CLASS("_TtC21ConsentViewController21ResourceNotFoundError")
@interface ResourceNotFoundError : GenericNetworkError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@end

enum SPActionType : NSInteger;

/// Action consists of <code>SPActionType</code> and an id. Those come from each action the user can take in the ConsentUI
SWIFT_CLASS("_TtC21ConsentViewController8SPAction")
@interface SPAction : NSObject
@property (nonatomic, readonly) enum SPActionType type;
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable consentLanguage;
@property (nonatomic, copy) NSURL * _Nullable pmURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// User actions. Its integer representation matches with what SourcePoint’s endpoints expect.
typedef SWIFT_ENUM(NSInteger, SPActionType, open) {
  SPActionTypeSaveAndExit = 1,
  SPActionTypePMCancel = 2,
  SPActionTypeAcceptAll = 11,
  SPActionTypeShowPrivacyManager = 12,
  SPActionTypeRejectAll = 13,
  SPActionTypeDismiss = 15,
  SPActionTypeRequestATTAccess = 16,
  SPActionTypeUnknown = 0,
};

enum SPPrivacyManagerTab : NSInteger;

SWIFT_PROTOCOL("_TtP21ConsentViewController6SPCCPA_")
@protocol SPCCPA
- (void)loadCCPAPrivacyManagerWithId:(NSString * _Nonnull)withId tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)ccpaApplies SWIFT_WARN_UNUSED_RESULT;
@end


/// The UserConsent class encapsulates the consent status, rejected vendor ids and rejected categories (purposes) ids.
/// important:
/// The <code>rejectedVendors</code> and <code>rejectedCategories</code> arrays will only be populated if the <code>status</code> is <code>.Some</code>.
/// That is, if the user has rejected <code>.All</code> or <code>.None</code> vendors/categories, those arrays will be empty.
SWIFT_CLASS("_TtC21ConsentViewController13SPCCPAConsent")
@interface SPCCPAConsent : NSObject
/// represents the default state of the consumer prior to seeing the consent message
/// seealso:
/// https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md#us-privacy-string-format
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultUsPrivacyString;)
+ (NSString * _Nonnull)defaultUsPrivacyString SWIFT_WARN_UNUSED_RESULT;
+ (SPCCPAConsent * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
/// Indicates if the user has rejected <code>.All</code>, <code>.Some</code> or <code>.None</code> of the vendors <em>and</em> categories.
@property (nonatomic, readonly) enum CCPAConsentStatus status;
/// The ids of the rejected vendors and categories. These can be found in SourcePoint’s dashboard
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rejectedVendors;
/// The ids of the rejected vendors and categories. These can be found in SourcePoint’s dashboard
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rejectedCategories;
/// the US Privacy String as described by the IAB
@property (nonatomic, readonly, copy) NSString * _Nonnull uspstring;
+ (SPCCPAConsent * _Nonnull)rejectedNone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStatus:(enum CCPAConsentStatus)status rejectedVendors:(NSArray<NSString *> * _Nonnull)rejectedVendors rejectedCategories:(NSArray<NSString *> * _Nonnull)rejectedCategories uspstring:(NSString * _Nonnull)uspstring OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SPCampaignEnv : NSInteger;

/// Contains information about the property/campaign.
SWIFT_CLASS("_TtC21ConsentViewController10SPCampaign")
@interface SPCampaign : NSObject
- (nonnull instancetype)initWithEnvironment:(enum SPCampaignEnv)environment targetingParams:(NSDictionary<NSString *, NSString *> * _Nonnull)targetingParams OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Tells the SDK if we should load stage or public campaigns.
/// <ul>
///   <li>
///     0 -> <code>SPCampaignEnv.Stage</code>
///   </li>
///   <li>
///     1 -> <code>SPCampaignEnv.Public</code>
///   </li>
/// </ul>
typedef SWIFT_ENUM(NSInteger, SPCampaignEnv, open) {
  SPCampaignEnvStage = 0,
  SPCampaignEnvPublic = 1,
};

typedef SWIFT_ENUM(NSInteger, SPCampaignType, open) {
  SPCampaignTypeGdpr = 0,
  SPCampaignTypeIos14 = 1,
  SPCampaignTypeCcpa = 2,
  SPCampaignTypeUnknown = 3,
};


/// Set <code>gdpr</code> and/or <code>ccpa</code> if you wish to cover any of those legislations.
/// It’s important to notice the campaign you passed as parameter needs to have
/// a active vendor list of that legislation.
SWIFT_CLASS("_TtC21ConsentViewController11SPCampaigns")
@interface SPCampaigns : NSObject
- (nonnull instancetype)initWithGdpr:(SPCampaign * _Nullable)gdpr ccpa:(SPCampaign * _Nullable)ccpa ios14:(SPCampaign * _Nullable)ios14 OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SPMessageViewController;
@class SPUserData;

SWIFT_PROTOCOL("_TtP21ConsentViewController17SPConsentDelegate_")
@protocol SPConsentDelegate
/// called when there’s a consent Message to be shown
- (void)onSPUIReady:(SPMessageViewController * _Nonnull)controller;
/// called when the SP UI is finished and can be dismissed
- (void)onSPUIFinished:(SPMessageViewController * _Nonnull)controller;
@optional
/// called after the user takes an action and the SDK receives consent data back from the server
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     consents: is the consent profile
///   </li>
/// </ul>
- (void)onConsentReadyWithUserData:(SPUserData * _Nonnull)userData;
/// called if something goes wrong during the entire lifecycle of the SDK
- (void)onErrorWithError:(SPError * _Nonnull)error;
@end


SWIFT_PROTOCOL("_TtP21ConsentViewController6SPGDPR_")
@protocol SPGDPR
- (void)loadGDPRPrivacyManagerWithId:(NSString * _Nonnull)withId tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)gdprApplies SWIFT_WARN_UNUSED_RESULT;
@end

@class SPGDPRConsent;

SWIFT_PROTOCOL("_TtP21ConsentViewController5SPSDK_")
@protocol SPSDK <SPCCPA, SPGDPR>
@property (nonatomic, readonly, strong) SPUserData * _Nonnull userData;
- (void)loadMessageForAuthId:(NSString * _Nullable)authId;
- (void)customConsentGDPRWithVendors:(NSArray<NSString *> * _Nonnull)vendors categories:(NSArray<NSString *> * _Nonnull)categories legIntCategories:(NSArray<NSString *> * _Nonnull)legIntCategories handler:(void (^ _Nonnull)(SPGDPRConsent * _Nonnull))handler;
@end

@class SPPropertyName;
enum SPMessageLanguage : NSInteger;

SWIFT_CLASS("_TtC21ConsentViewController16SPConsentManager")
@interface SPConsentManager : NSObject <SPSDK>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VERSION;)
+ (NSString * _Nonnull)VERSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL shouldCallErrorMetrics;)
+ (BOOL)shouldCallErrorMetrics SWIFT_WARN_UNUSED_RESULT;
+ (void)setShouldCallErrorMetrics:(BOOL)value;
@property (nonatomic, readonly, strong) SPUserData * _Nonnull userData;
+ (void)clearAllData;
- (nonnull instancetype)initWithAccountId:(NSInteger)accountId propertyName:(SPPropertyName * _Nonnull)propertyName campaigns:(SPCampaigns * _Nonnull)campaigns delegate:(id <SPDelegate> _Nullable)delegate;
/// Instructs the privacy manager to be displayed with this tab.
/// By default the SDK will use the defult tab of PM
@property (nonatomic) enum SPPrivacyManagerTab privacyManagerTab;
/// Instructs the message to be displayed in this language. If the translation is missing, the fallback will be English.
/// By default the SDK will use the locale defined by the WebView
@property (nonatomic) enum SPMessageLanguage messageLanguage;
- (void)loadMessageForAuthId:(NSString * _Nullable)authId;
- (void)loadGDPRPrivacyManagerWithId:(NSString * _Nonnull)id tab:(enum SPPrivacyManagerTab)tab;
- (void)loadCCPAPrivacyManagerWithId:(NSString * _Nonnull)id tab:(enum SPPrivacyManagerTab)tab;
- (BOOL)gdprApplies SWIFT_WARN_UNUSED_RESULT;
- (BOOL)ccpaApplies SWIFT_WARN_UNUSED_RESULT;
- (void)customConsentGDPRWithVendors:(NSArray<NSString *> * _Nonnull)vendors categories:(NSArray<NSString *> * _Nonnull)categories legIntCategories:(NSArray<NSString *> * _Nonnull)legIntCategories handler:(void (^ _Nonnull)(SPGDPRConsent * _Nonnull))handler;
- (void)onError:(SPError * _Nonnull)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP21ConsentViewController19SPConsentUIDelegate_")
@protocol SPConsentUIDelegate
/// called when the user takes an action in the SP UI
/// \param action the user action
///
- (void)onAction:(SPAction * _Nonnull)action from:(SPMessageViewController * _Nonnull)controller;
@end


/// Have a look at <a href="https://github.com/SourcePointUSA/CCPA_iOS_SDK/wiki/SDKs-Lifecycle-methods">SDKs Lifecycle</a>
SWIFT_PROTOCOL("_TtP21ConsentViewController10SPDelegate_")
@protocol SPDelegate <SPConsentDelegate, SPConsentUIDelegate>
@end



@class SPGDPRVendorGrant;

/// SPGDPRConsent encapsulates all consent data from a user.
SWIFT_CLASS("_TtC21ConsentViewController13SPGDPRConsent")
@interface SPGDPRConsent : NSObject
+ (SPGDPRConsent * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, SPGDPRVendorGrant *> * _Nonnull vendorGrants;
/// The iAB consent string.
@property (nonatomic, readonly, copy) NSString * _Nonnull euconsent;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Encapuslates data about a particular vendor being “granted” based on its purposes
SWIFT_CLASS("_TtC21ConsentViewController17SPGDPRVendorGrant")
@interface SPGDPRVendorGrant : NSObject
/// if all purposes are granted, the vendorGrant will be set to <code>true</code>
@property (nonatomic, readonly) BOOL granted;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSNumber *> * _Nonnull purposeGrants;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithGranted:(BOOL)granted purposeGrants:(NSDictionary<NSString *, NSNumber *> * _Nonnull)purposeGrants OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Maps <code>ATTrackingManager.requestTrackingAuthorization</code> into our own enum.
/// It covers also the case when <code>ATTrackingManager.AuthorizationStatus</code> is not available.
typedef SWIFT_ENUM(NSInteger, SPIDFAStatus, open) {
/// the user hasn’t been prompted about the IDFA yet
  SPIDFAStatusUnknown = 0,
/// the user accepted being tracked
  SPIDFAStatusAccepted = 1,
/// the user denied access to IDFA
  SPIDFAStatusDenied = 2,
/// the IDFA is not available in this version of the OS
  SPIDFAStatusUnavailable = 3,
};

/// Languages supported by Message and PM
typedef SWIFT_ENUM(NSInteger, SPMessageLanguage, open) {
  SPMessageLanguageBrowserDefault = 0,
  SPMessageLanguageEnglish = 1,
  SPMessageLanguageBulgarian = 2,
  SPMessageLanguageCatalan = 3,
  SPMessageLanguageChinese = 4,
  SPMessageLanguageCroatian = 5,
  SPMessageLanguageCzech = 6,
  SPMessageLanguageDanish = 7,
  SPMessageLanguageDutch = 8,
  SPMessageLanguageEstonian = 9,
  SPMessageLanguageFinnish = 10,
  SPMessageLanguageFrench = 11,
  SPMessageLanguageGaelic = 12,
  SPMessageLanguageGerman = 13,
  SPMessageLanguageGreek = 14,
  SPMessageLanguageHungarian = 15,
  SPMessageLanguageIcelandic = 16,
  SPMessageLanguageItalian = 17,
  SPMessageLanguageJapanese = 18,
  SPMessageLanguageLatvian = 19,
  SPMessageLanguageLithuanian = 20,
  SPMessageLanguageNorwegian = 21,
  SPMessageLanguagePolish = 22,
  SPMessageLanguagePortuguese = 23,
  SPMessageLanguageRomanian = 24,
  SPMessageLanguageRussian = 25,
  SPMessageLanguageSerbian_Cyrillic = 26,
  SPMessageLanguageSerbian_Latin = 27,
  SPMessageLanguageSlovakian = 28,
  SPMessageLanguageSlovenian = 29,
  SPMessageLanguageSpanish = 30,
  SPMessageLanguageSwedish = 31,
  SPMessageLanguageTurkish = 32,
};


SWIFT_CLASS("_TtC21ConsentViewController23SPMessageViewController")
@interface SPMessageViewController : UIViewController <MessageController>
@property (nonatomic) enum SPCampaignType campaignType;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)loadMessage;
- (void)loadPrivacyManagerWithUrl:(NSURL * _Nonnull)url;
- (void)closePrivacyManager;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC21ConsentViewController29SPNativeMessageViewController")
@interface SPNativeMessageViewController : SPMessageViewController
- (nullable instancetype)initWithMessageContents:(GDPRMessage * _Nonnull)messageContents consentViewController:(id <GDPRMessageUIDelegate> _Nonnull)consentViewController OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@end

/// Supported privacy manager tabs in PM
typedef SWIFT_ENUM(NSInteger, SPPrivacyManagerTab, open) {
  SPPrivacyManagerTabDefault = 0,
  SPPrivacyManagerTabPurposes = 1,
  SPPrivacyManagerTabVendors = 2,
  SPPrivacyManagerTabFeatures = 3,
};


/// SPPropertyName is the exact name of your property as created in SourcePoint’s dashboard.
/// important:
/// notice that it can only contain letters, numbers, . (dots), : (semicolons),
/// <ul>
///   <li>
///     (dashes) and / (slashes). The constructor will validate upon that and throw an error otherwise.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC21ConsentViewController14SPPropertyName")
@interface SPPropertyName : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// \param rawValue the exact name of your property as created in SourcePoint’s dashboard.
///
///
/// throws:
/// <code>InvalidArgumentError</code> if the property name contain anything other than letters, numbers, . (dots), : (semicolons) and / (slashes).
- (nullable instancetype)init:(NSString * _Nonnull)rawValue error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21ConsentViewController10SPUserData")
@interface SPUserData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC21ConsentViewController37UnableToInjectMessageIntoRenderingApp")
@interface UnableToInjectMessageIntoRenderingApp : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC21ConsentViewController22UnableToLoadJSReceiver")
@interface UnableToLoadJSReceiver : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



@interface WKWebView (SWIFT_EXTENSION(ConsentViewController))
/// Injects the cookie <code>authId</code> in the webview before loading its content.
/// SourcePoint’s web SDK reads the <code>authId</code> cookie and set everything up in the webview context.
- (void)setConsentForAuthId:(NSString * _Nonnull)authId;
/// Reads the value of the cookie authId
- (void)getAuthIdWithCompletionHandler:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC21ConsentViewController12WebViewError")
@interface WebViewError : SPError
@property (nonatomic, readonly, copy) NSString * _Nonnull spCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
