# This Config is used when running swiftlint from within GitHub Actions
# It needs to be called from the root folder of the project and uses
# the "github-actions-logging" reporter.
# Make sure the rules are always in sync with the one from Example/.swiftlint.yml

disabled_rules:
  - switch_case_alignment
included: # paths to include during linting. `--path` is ignored if present.
 - ConsentViewController/Classes
 - Example/ConsentViewController_ExampleTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
identifier_name:
  min_length:
    - 1
    - 1
  allowed_symbols:
    - _
  validates_start_with_lowercase: false
line_length:
  warning: 180
  error: 220
reporter: "github-actions-logging"
