# This Config is used when running swiftlint from within GitHub Actions
# It needs to be called from the root folder of the project and uses
# the "github-actions-logging" reporter.
# Make sure the rules are always in sync with the one from Example/.swiftlint.yml

disabled_rules:
  - switch_case_alignment
  - void_function_in_ternary
  - vertical_whitespace_between_cases
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - force_unwrapping
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition
included: # paths to include during linting. `--path` is ignored if present.
 - ConsentViewController/Classes
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Example/*
  - Example/AuthExample
  - Example/Pods
  - Example/SourcePointMetaAppUITests
  - Example/SourcePointMetaApp
identifier_name:
  min_length:
    - 1
    - 1
  allowed_symbols:
    - _
  validates_start_with_lowercase: false
line_length:
  warning: 180
  error: 220
reporter: "github-actions-logging"
