//
//  PMJSONData.swift
//  ConsentViewController-tvOS
//
//  Created by Vilas on 20/04/21.
//

import Foundation

// swiftlint:disable all

public let AppleOTTJSON = """
{
   "homeView":{
      "id":"HomeView",
      "showPrivacyPolicyBtn":false,
      "style":{
         "backgroundColor":"#e5e8ef"
      },
      "components":[
         {
            "id":"BackButton",
            "type":"BackButton",
            "text":"Back",
            "style":{
               "backgroundColor":"#ffffff",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"HeaderText",
            "type":"Text",
            "text":"Privacy",
            "style":{
               "font":{
                  "fontSize":70,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"CategoriesDescriptionText",
            "type":"Text",
            "text":"We and our partners use device identifiers or similar technologies on the app and to collect and use personal data (e.g., your IP address). If you consent, the device identifiers or or the information can be stored locally or accessed on your device for the purpose described below. You can click “Accept All” or “manage Preferences” to customize your consent.",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"CategoriesSubDescriptionText",
            "type":"Text",
            "text":"We and our partners process personal data to",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"600",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"AcceptAllButton",
            "type":"Button",
            "text":"Accept All",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"NavCategoriesButton",
            "type":"Button",
            "text":"Manage Preferences",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"NavVendorsButton",
            "type":"Button",
            "text":"Our Partners",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"NavPrivacyPolicyButton",
            "type":"Button",
            "text":"Privacy Policy",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"LogoImage",
            "type":"Image",
            "src":"site.com/logo.png",
            "style":{
               "width":250
            }
         },
         {
            "id":"CategoryButtons",
            "type":"Long-Button",
            "textDetails":{
               "onText":"",
               "offText":"",
               "customCategoryText":"Custom",
               "customVendorText":""
            },
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#f1f2f6"
            }
         }
      ]
   },
   "categoriesView":{
      "id":"CategoriesView",
      "style":{
         "backgroundColor":"#e5e8ef"
      },
      "components":[
         {
            "id":"BackButton",
            "type":"BackButton",
            "text":"Back",
            "style":{
               "backgroundColor":"#ffffff",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"HeaderText",
            "type":"Text",
            "text":"Manage Preferences",
            "style":{
               "font":{
                  "fontSize":70,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"AcceptAllButton",
            "type":"Button",
            "text":"Accept All",
            "style":{
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"SaveButton",
            "type":"Button",
            "text":"Save & Exit",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"CategoriesHeader",
            "type":"Text",
            "text":"We and our partners process person data to:",
            "style":{
               "fontSize":30,
               "fontWeight":"600",
               "color":"#22243b",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"PurposesHeader",
            "type":"Text",
            "text":"Purposes",
            "style":{
               "fontSize":30,
               "fontWeight":"400",
               "color":"#828386",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"PurposesDefinition",
            "type":"Text",
            "text":"You give affirmative action to indicate that we can use your data for this purpose",
            "style":{
               "fontSize":30,
               "fontWeight":"400",
               "color":"#22243b",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"FeaturesHeader",
            "type":"Text",
            "text":"Features",
            "style":{
               "fontSize":30,
               "fontWeight":"400",
               "color":"#828386",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"FeaturesDefinition",
            "type":"Text",
            "text":"Features are a use of the data that you have already agreed to share with us",
            "style":{
               "fontSize":30,
               "fontWeight":"400",
               "color":"#22243b",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"SpecialPurposesHeader",
            "type":"Text",
            "text":"Special Purposes",
            "style":{
               "fontSize":30,
               "fontWeight":"400",
               "color":"#828386",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"SpecialPurposesDefinition",
            "type":"Text",
            "text":"We have a need to use your data for this processing purpose that is required for us to deliver services to you",
            "style":{
               "fontSize":30,
               "fontWeight":"400",
               "color":"#22243b",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"SpecialFeaturesHeader",
            "type":"Text",
            "text":"Special features",
            "style":{
               "fontSize":30,
               "fontWeight":"400",
               "color":"#828386",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"SpecialFeaturesDefintion",
            "type":"Text",
            "text":"Special Features are purposes that require your explicit content",
            "style":{
               "fontSize":30,
               "fontWeight":"400",
               "color":"#22243b",
               "fontFamily":"helvetica"
            }
         },
         {
            "id":"CategoriesSlider",
            "type":"Slider",
            "sliderDetails":{
               "consentText":"CONSENT",
               "legitInterestText":"LEGITIMATE INTEREST"
            },
            "style":{
               "backgroundColor":"#d8d9dd",
               "activeBackgroundColor":"#6f11d4",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               },
               "activeFont":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#ffffff",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"CategoryButton",
            "type":"LongButton",
            "textDetails":{
               "onText":"On",
               "offText":"Off",
               "customCategoryText":"Custom",
               "customVendorText":""
            },
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#f1f2f6"
            }
         }
      ]
   },
   "vendorsView":{
      "id":"VendorsView",
      "style":{
         "backgroundColor":"#e5e8ef"
      },
      "components":[
         {
            "id":"HeaderText",
            "type":"Text",
            "text":"Our Partners",
            "style":{
               "font":{
                  "fontSize":70,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"BackButton",
            "type":"BackButton",
            "text":"Back",
            "style":{
               "backgroundColor":"#ffffff",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"AcceptAllButton",
            "type":"Button",
            "text":"Accept All",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"SaveButton",
            "type":"Button",
            "text":"Save & Exit",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"CategoriesSlider",
            "type":"Slider",
            "sliderDetails":{
               "consentText":"CONSENT",
               "legitInterestText":"LEGITIMATE INTEREST"
            },
            "style":{
               "backgroundColor":"#d8d9dd",
               "activeBackgroundColor":"#6f11d4",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               },
               "activeFont":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#ffffff",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"VendorsHeader",
            "type":"Text",
            "text":"Partners",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"600",
                  "color":"#22243b",
                  "fontFamily":"helvetica"
               }
            }
         }
      ]
   },
   "categoryDetails":{
      "id":"CategoryDetails",
      "style":{
         "backgroundColor":"#e5e8ef"
      },
      "components":[
         {
            "id":"BackButton",
            "type":"BackButton",
            "text":"Back",
            "style":{
               "backgroundColor":"#ffffff",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"OnButton",
            "type":"Button",
            "text":"On",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"OffButton",
            "type":"Button",
            "text":"Off",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"Header",
            "type":"Text",
            "text":"Partners",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"600",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"CategoryDescription",
            "type":"Text",
            "text":"",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         }
      ]
   },
   "vendorDetails":{
      "id":"VendorDetails",
      "style":{
         "backgroundColor":"#e5e8ef"
      },
      "components":[
         {
            "id":"BackButton",
            "type":"BackButton",
            "text":"Back",
            "style":{
               "backgroundColor":"#ffffff",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"OnText",
            "type":"Text",
            "text":"On",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"OffText",
            "type":"Text",
            "text":"Off",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
            "id":"PurposesText",
            "type":"Text",
            "text":"Purposes",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#828386",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"VendorLongButton",
            "type":"LongButton",
            "textDetails":{
               "onText":"On",
               "offText":"Off",
               "customCategoryText":"Custom",
               "customVendorText":"Other"
            },
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#f1f2f6"
            }
         },
         {
            "id":"SpecialPurposes",
            "type":"Text",
            "text":"Special Purposes",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#828386",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"SpecialFeatures",
            "type":"Text",
            "text":"Special Features",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#828386",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"LegitInterests",
            "type":"Text",
            "text":"Legitimate Interests",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#828386",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"VendorDescription",
            "type":"Text",
            "text":"",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"QrInstructions",
            "type":"Text",
            "text":"To scan use your camera app or a QR code reader on your device",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               }
            }
         }
      ]
   },
   "privacyPolicyView":{
      "id":"PrivacyPolicyView",
      "style":{
         "backgroundColor":"#e5e8ef"
      },
      "components":[
         {
            "id":"BackButton",
            "type":"BackButton",
            "text":"Back",
            "style":{
               "backgroundColor":"#ffffff",
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"HeaderText",
            "type":"Text",
            "text":"Privacy Policy",
            "style":{
               "font":{
                  "fontSize":70,
                  "fontWeight":"400",
                  "color":"#000000",
                  "fontFamily":"helvetica"
               }
            }
         },
         {
            "id":"CloseButton",
            "type":"Button",
            "text":"Close",
            "style":{
               "font":{
                  "fontSize":30,
                  "fontWeight":"400",
                  "fontFamily":"helvetica"
               },
               "onFocusBackgroundColor":"#ffffff",
               "onUnfocusBackgroundColor":"#575757",
               "onFocusTextColor":"#000000",
               "onUnfocusTextColor":"#ffffff"
            }
         },
         {
             "id":"Body",
             "type":"Text",
             "text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas at eros at ullamcorper. Aliquam porttitor urna augue, a bibendum risus elementum et. Proin suscipit pulvinar mauris in ullamcorper. Suspendisse et porttitor tortor, eu interdum augue. Nunc sollicitudin dui nunc, nec elementum lectus auctor at. Etiam laoreet lacus quis ante finibus pulvinar. Suspendisse potenti. Aenean ac suscipit nunc. Proin elementum elit id porttitor fringilla. Vivamus consequat scelerisque rhoncus. Suspendisse posuere id enim vel vulputate. Nulla consequat lobortis efficitur. Cras in augue quis neque laoreet condimentum at id felis. Mauris pretium viverra ligula, non ullamcorper lacus ullamcorper id.Mauris et lorem eget erat fermentum ultrices. Pellentesque gravida, sem vel luctus condimentum, neque nibh lacinia neque, ac tempus sapien orci ut odio. Donec bibendum erat quis augue dignissim, rutrum fringilla sem egestas. Sed eu sem erat. Mauris sit amet lectus blandit, sollicitudin dui vel, fermentum velit. Suspendisse potenti. Sed vestibulum malesuada lorem posuere scelerisque. Suspendisse egestas nisl non neque posuere tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas at eros at ullamcorper. Aliquam porttitor urna augue, a bibendum risus elementum et. Proin suscipit pulvinar mauris in ullamcorper. Suspendisse et porttitor tortor, eu interdum augue. Nunc sollicitudin dui nunc, nec elementum lectus auctor at. Etiam laoreet lacus quis ante finibus pulvinar. Suspendisse potenti. Aenean ac suscipit nunc. Proin elementum elit id porttitor fringilla. Vivamus consequat scelerisque rhoncus. Suspendisse posuere id enim vel vulputate. Nulla consequat lobortis efficitur. Cras in augue quis neque laoreet condimentum at id felis. Mauris pretium viverra ligula, non ullamcorper lacus ullamcorper id.",
             "style":{}
         }
      ]
   }
}
"""
